version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:15-alpine
    volumes:
      - ./scripts/postgresql:/docker-entrypoint-initdb.d
      - postgres_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_MULTIPLE_DATABASES: ${PG_DB_NAME},${PG_DB_NAME}_test
    ports:
      - 5432:5432

  redis:
    container_name: redis
    image: redis:6-alpine
    volumes:
      - redis_volume:/data
    ports:
      - 6379:6379

  adonis_app:
    container_name: adonis_app
    restart: always
    depends_on:
      - postgres
      - redis
    build:
      context: .
      target: dependencies
    ports:
      - ${PORT}:${PORT}
      - 9229:9229
    env_file:
      - .env
    environment:
      - PG_HOST=postgres
      - REDIS_HOST=redis
    volumes:
      - ./:/home/node/app
      - ./node_modules:/home/node/app/node_modules
    command: dumb-init node ace serve --watch --node-args="--inspect=0.0.0.0"

  video_processing:
    container_name: video_processing
    restart: always
    depends_on:
      - redis
    build:
      context: ../video
      target: dependencies
    env_file:
      - .env
    volumes:
      - ../video:/home/node/app
      - ../video/node_modules:/home/node/app/node_modules
    command: npm run dev

volumes:
  postgres_volume:
  redis_volume:
