version: "3.8"

services:
  api:
    build:
      context: ./api
      target: development
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./api:/app
      - uploads-volume:/app/tmp/uploads
    ports:
      - ${PORT}:${PORT}

  db:
    image: postgres:15-alpine
    volumes:
      - ./api/scripts/docker-postgresql-multiple-databases:/docker-entrypoint-initdb.d
      - db-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_MULTIPLE_DATABASES

volumes:
  db-volume:
  uploads-volume:
